language: cpp

services:
  - docker

sudo: required
dist: trusty
osx_image: xcode9.2

env:
  global:
    - QPMX_CACHE_DIR=$HOME/.qpmx-cache
    - QT_VER=5.10.1
    - EXTRA_MODULES=".qtremoteobjects .skycoder42.datasync .skycoder42.mvvm"
    - DOCKER_IMAGE=full

matrix:
  include:
    - os: linux
      env:
        - PLATFORM=gcc_64
    - os: linux
      env:
        - PLATFORM=android_armv7
    - os: linux
      env:
        - PLATFORM=android_x86
    - os: osx
      env:
        - PLATFORM=clang_64

before_install:
  - git clone https://github.com/Skycoder42/QtModules.git ./qtmodules-travis
  - ./ci/setup-travis.sh
  - travis_wait 40 ./qtmodules-travis/ci/$TRAVIS_OS_NAME/setup.sh

script:
  - ./qtmodules-travis/ci/$TRAVIS_OS_NAME/build.sh

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - rm -fr $QPMX_CACHE_DIR/locks
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
    - $QPMX_CACHE_DIR
