language: cpp

services:
  - docker

sudo: required
dist: trusty
osx_image: xcode9.4

env:
  global:
    - QPMX_CACHE_DIR=$HOME/.qpmx-cache
    - QT_VER_MINOR=5.11
    - QT_VER=${QT_VER_MINOR}.1
    - OPENSSL_VERSION=1.0.2p
    - EXTRA_MODULES=".skycoder42"
    - DOCKER_IMAGE=full
    - NO_TESTS=true

matrix:
  include:
    - os: linux
      env:
        - PLATFORM=gcc_64
        - QMAKE_FLAGS="PREFIX=/deploy CONFIG+=no_quick"
    - os: linux
      env:
        - PLATFORM=flatpak
        - DOCKER_IMAGE=
        - DOCKER_IMAGE_BASE="base/archlinux:latest"
        - FLATPAK_MANIFEST=flatpak/de.skycoder42.syrem.json
    - os: linux
      env:
        - PLATFORM=android_armv7
    - os: linux
      env:
        - PLATFORM=android_x86
    - os: osx
      env:
        - PLATFORM=clang_64
        - QMAKE_FLAGS="PREFIX=/deploy CONFIG+=no_quick"

before_install:
  - git clone https://github.com/Skycoder42/QtModules.git ./qtmodules-travis
  - travis_wait 40 ./qtmodules-travis/ci/$TRAVIS_OS_NAME/setup.sh

script:
  - ./ci/travis_init.sh
  - ./qtmodules-travis/ci/$TRAVIS_OS_NAME/build.sh
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then ./ci/travis_postbuild.sh; fi

before_deploy:
  - ./ci/travis_deploy.sh
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: g1X+UvDS+0IRyXwkbun9UKdq9eCgSvMFk0+wzpPhZ3HG8w21xfVs7Q8XSHzbm1uA/YiWgrOh6y8ENTB8C0PNS92wg9A/t6yusD7v3dpuTOygYBbMKTsQty6JzZIZY+zGsRKa0JWZzW70vy3zqokXvETcMAcVKFqr6zMv7w1aiHJr5V+cY/9pRgqa7s/61Fg1C3ZbOQZLlb1CDWDNk1N0gr/7FcmI2rf6nxp+GJLFk4uc7cdlc5TBotVLsZkGpJ9j064HnAWY1gzutbw4fY2bUXDPzU7ycpjzq+9ohEpaSR95C7M1nLul75vbsJtLeXM9NGsDXX6ATMz5Og7aF3ZGWlQUAdmAlrGB1d6YJOZ8V1Qrm46AT5wBTqt8kr0eWtDyx4VQAqrcBIM+ZA9TiiqYeiu3WlIQm2ncSx+c/cUuFWyx7+Jo++uDrr0vt1te5HtCPaped8PBsrvVkUj5pKWg+sDTybMHmyOtrbjByFvL1Gtsitl358gT69EfdmkGHJTmWa9quz/66JBoz7HkEFn9UVb1STOqWMjtOW0awFSvs4K7N7oaKRXLRLrhIC/W0bGr4MKOfH/JV0dt2/3kN1q8HHJ5PsXGlXjvKwafBc2lMczIOhUfozCP/p7u/xbEAgToCgb+YFE9c7n5MMg2RCtrWWXK5slpBOw3w9/6ae4uNVo=
  file_glob: true
  file:
    - ./install/syrem-*.dmg
    - ./install/syrem-*.apk
    - ./install/flatpak_build.tar.xz
  on:
    repo: Skycoder42/Syrem
    tags: true

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
  - rm -rf $QPMX_CACHE_DIR/locks
  - rm -rf $QPMX_CACHE_DIR/tmp
  - sudo rm -rf flatpak-build/.flatpak-builder/build
  - sudo rm -rf flatpak-build/.flatpak-builder/rofiles
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
    - $QPMX_CACHE_DIR
    - flatpak-build/.flatpak-builder
