image:
  - Visual Studio 2017

version: build-{build}

environment:
  QT_VER: 5.10.1
  EXTRA_MODULES: .qtremoteobjects;.skycoder42.datasync;.skycoder42.mvvm

  matrix:
    - PLATFORM: msvc2017_64

install:
  - git clone https://github.com/Skycoder42/QtModules.git .\qtmodules-travis
  - .\qtmodules-travis\ci\win\setup.bat

build_script:
  - .\qtmodules-travis\ci\win\build.bat

cache:
  - 'C:\Users\appveyor\AppData\Local\Skycoder42\qpmx\cache -> appveyor.yml'
